In [49]:
import numpy as np
import pandas as pd
import seaborn as sns

In [50]:
df= pd.read_csv("7_real_estate_prices.csv")

In [51]:
df.describe

<bound method NDFrame.describe of          property_id listing_date  property_type     city neighborhood_tier  \
0      PROP_00000001   17-09-2023          Condo   Denver           Premium
1      PROP_00000002   27-04-2023  Single Family  Seattle           Premium
2      PROP_00000003   28-11-2023  Single Family   Austin           Average
3      PROP_00000004   15-02-2023  Single Family   Austin              Good
4      PROP_00000005   07-11-2023  Single Family  Atlanta           Premium
...              ...          ...            ...      ...               ...
14995  PROP_00014996   03-11-2023      Townhouse  Seattle           Average
14996  PROP_00014997   19-01-2023  Single Family  Seattle           Premium
14997  PROP_00014998   02-01-2023          Condo   Denver              Good
14998  PROP_00014999   21-08-2023  Single Family  Atlanta              Good
14999  PROP_00015000   19-05-2023  Single Family  Seattle        Developing

       zipcode_crime_rate  school_rating  distance_to_downtown_miles  \
0                    1.33              6                        33.5
1                    1.67              6                         9.2
2                    1.16              6                         2.1
3                    0.97              8                         2.8
4                    2.64              7                        10.2
...                   ...            ...                         ...
14995                1.34              3                         3.7
14996                2.13              8                        12.5
14997                2.78              7                         7.9
14998                0.08              6                         3.5
14999               14.38              8                        14.6

       walk_score  bedrooms  ...  days_on_market  listing_season  \
0              38         4  ...              37          Summer
1              85         2  ...               5            Fall
2              98         6  ...               7            Fall
3              46         4  ...              86          Summer
4              54         3  ...              88          Spring
...           ...       ...  ...             ...             ...
14995          30         4  ...              18          Spring
14996          16         4  ...              49          Spring
14997          44         3  ...              11            Fall
14998          32         3  ...              21          Spring
14999          69         3  ...               3          Spring

       market_trend  interest_rate  has_fireplace  has_patio_deck  \
0            Stable           6.43             No             Yes
1            Stable           7.15            Yes             Yes
2            Rising           7.48             No             Yes
3            Stable           6.62            Yes              No
4            Rising           5.90            Yes              No
...             ...            ...            ...             ...
14995        Rising           5.73            Yes             Yes
14996        Rising           5.93            Yes             Yes
14997        Rising           6.16             No              No
14998        Rising           6.29             No             Yes
14999        Stable           7.00             No             Yes

       has_security_system hoa_fees sale_price high_value_property
0                      Yes      0.0     822296                 Yes
1                       No    307.0     687536                  No
2                       No      0.0    1207336                 Yes
3                       No      0.0     938047                 Yes
4                       No    160.0     691008                  No
...                    ...      ...        ...                 ...
14995                  Yes      0.0     714235                  No
14996                   No      0.0     977953                 Yes
14997                   No      0.0     750095                  No
14998                   No      0.0     716925                  No
14999                  Yes      0.0     625675                  No

[15000 rows x 35 columns]>

In [52]:
df.columns

Index(['property_id', 'listing_date', 'property_type', 'city',
       'neighborhood_tier', 'zipcode_crime_rate', 'school_rating',
       'distance_to_downtown_miles', 'walk_score', 'bedrooms', 'bathrooms',
       'square_feet', 'lot_size_sqft', 'stories', 'garage_spaces',
       'year_built', 'house_age', 'has_basement', 'has_pool',
       'overall_condition', 'kitchen_quality', 'hvac_condition',
       'roof_condition', 'renovation_year', 'years_since_renovation',
       'days_on_market', 'listing_season', 'market_trend', 'interest_rate',
       'has_fireplace', 'has_patio_deck', 'has_security_system', 'hoa_fees',
       'sale_price', 'high_value_property'],
      dtype='str')

In [53]:
df.info(max_cols=None)

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_id                 15000 non-null  str
 1   listing_date                15000 non-null  str
 2   property_type               15000 non-null  str
 3   city                        15000 non-null  str
 4   neighborhood_tier           15000 non-null  str
 5   zipcode_crime_rate          15000 non-null  float64
 6   school_rating               15000 non-null  int64
 7   distance_to_downtown_miles  15000 non-null  float64
 8   walk_score                  15000 non-null  int64
 9   bedrooms                    15000 non-null  int64
 10  bathrooms                   15000 non-null  float64
 11  square_feet                 14250 non-null  float64
 12  lot_size_sqft               15000 non-null  int64
 13  stories                     15000 non-null  int64
 14  garage_spaces               15000 non-null  int64
 15  year_built                  15000 non-null  int64
 16  house_age                   15000 non-null  int64
 17  has_basement                15000 non-null  str
 18  has_pool                    15000 non-null  str
 19  overall_condition           15000 non-null  str
 20  kitchen_quality             15000 non-null  str
 21  hvac_condition              15000 non-null  str
 22  roof_condition              15000 non-null  str
 23  renovation_year             6495 non-null   float64
 24  years_since_renovation      15000 non-null  int64
 25  days_on_market              15000 non-null  int64
 26  listing_season              15000 non-null  str
 27  market_trend                15000 non-null  str
 28  interest_rate               15000 non-null  float64
 29  has_fireplace               15000 non-null  str
 30  has_patio_deck              15000 non-null  str
 31  has_security_system         15000 non-null  str
 32  hoa_fees                    14250 non-null  float64
 33  sale_price                  15000 non-null  int64
 34  high_value_property         15000 non-null  str
dtypes: float64(7), int64(11), str(17)
memory usage: 4.0 MB

In [54]:
unique_values = df['property_type'].unique()
unique_values

<StringArray>
['Condo', 'Single Family', 'Townhouse', 'Multi-Family']
Length: 4, dtype: str

In [55]:
null_columns = df.columns[df.isnull().any()]
print(list(null_columns))

['square_feet', 'renovation_year', 'hoa_fees']

In [56]:
df['hoa_fees'] = df['hoa_fees'].fillna(0).where(df['property_type']!="Condo")
df

,property_id,listing_date,property_type,city,neighborhood_tier,zipcode_crime_rate,school_rating,distance_to_downtown_miles,walk_score,bedrooms,...,days_on_market,listing_season,market_trend,interest_rate,has_fireplace,has_patio_deck,has_security_system,hoa_fees,sale_price,high_value_property
0,PROP_00000001,17-09-2023,Condo,Denver,Premium,1.33,6,33.5,38,4,...,37,Summer,Stable,6.43,No,Yes,Yes,NaN,822296,Yes
1,PROP_00000002,27-04-2023,Single Family,Seattle,Premium,1.67,6,9.2,85,2,...,5,Fall,Stable,7.15,Yes,Yes,No,307.0,687536,No
2,PROP_00000003,28-11-2023,Single Family,Austin,Average,1.16,6,2.1,98,6,...,7,Fall,Rising,7.48,No,Yes,No,0.0,1207336,Yes
3,PROP_00000004,15-02-2023,Single Family,Austin,Good,0.97,8,2.8,46,4,...,86,Summer,Stable,6.62,Yes,No,No,0.0,938047,Yes
4,PROP_00000005,07-11-2023,Single Family,Atlanta,Premium,2.64,7,10.2,54,3,...,88,Spring,Rising,5.90,Yes,No,No,160.0,691008,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,PROP_00014996,03-11-2023,Townhouse,Seattle,Average,1.34,3,3.7,30,4,...,18,Spring,Rising,5.73,Yes,Yes,Yes,0.0,714235,No
14996,PROP_00014997,19-01-2023,Single Family,Seattle,Premium,2.13,8,12.5,16,4,...,49,Spring,Rising,5.93,Yes,Yes,No,0.0,977953,Yes
14997,PROP_00014998,02-01-2023,Condo,Denver,Good,2.78,7,7.9,44,3,...,11,Fall,Rising,6.16,No,No,No,NaN,750095,No
14998,PROP_00014999,21-08-2023,Single Family,Atlanta,Good,0.08,6,3.5,32,3,...,21,Spring,Rising,6.29,No,Yes,No,0.0,716925,No
14999,PROP_00015000,19-05-2023,Single Family,Seattle,Developing,14.38,8,14.6,69,3,...,3,Spring,Stable,7.00,No,Yes,Yes,0.0,625675,No

In [57]:
df['square_feet'] = df['square_feet'].fillna( df['lot_size_sqft']  )
df

,property_id,listing_date,property_type,city,neighborhood_tier,zipcode_crime_rate,school_rating,distance_to_downtown_miles,walk_score,bedrooms,...,days_on_market,listing_season,market_trend,interest_rate,has_fireplace,has_patio_deck,has_security_system,hoa_fees,sale_price,high_value_property
0,PROP_00000001,17-09-2023,Condo,Denver,Premium,1.33,6,33.5,38,4,...,37,Summer,Stable,6.43,No,Yes,Yes,NaN,822296,Yes
1,PROP_00000002,27-04-2023,Single Family,Seattle,Premium,1.67,6,9.2,85,2,...,5,Fall,Stable,7.15,Yes,Yes,No,307.0,687536,No
2,PROP_00000003,28-11-2023,Single Family,Austin,Average,1.16,6,2.1,98,6,...,7,Fall,Rising,7.48,No,Yes,No,0.0,1207336,Yes
3,PROP_00000004,15-02-2023,Single Family,Austin,Good,0.97,8,2.8,46,4,...,86,Summer,Stable,6.62,Yes,No,No,0.0,938047,Yes
4,PROP_00000005,07-11-2023,Single Family,Atlanta,Premium,2.64,7,10.2,54,3,...,88,Spring,Rising,5.90,Yes,No,No,160.0,691008,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,PROP_00014996,03-11-2023,Townhouse,Seattle,Average,1.34,3,3.7,30,4,...,18,Spring,Rising,5.73,Yes,Yes,Yes,0.0,714235,No
14996,PROP_00014997,19-01-2023,Single Family,Seattle,Premium,2.13,8,12.5,16,4,...,49,Spring,Rising,5.93,Yes,Yes,No,0.0,977953,Yes
14997,PROP_00014998,02-01-2023,Condo,Denver,Good,2.78,7,7.9,44,3,...,11,Fall,Rising,6.16,No,No,No,NaN,750095,No
14998,PROP_00014999,21-08-2023,Single Family,Atlanta,Good,0.08,6,3.5,32,3,...,21,Spring,Rising,6.29,No,Yes,No,0.0,716925,No
14999,PROP_00015000,19-05-2023,Single Family,Seattle,Developing,14.38,8,14.6,69,3,...,3,Spring,Stable,7.00,No,Yes,Yes,0.0,625675,No

In [58]:
df_cleaned = df.dropna(subset=['hoa_fees'])
df_cleaned.info()

<class 'pandas.DataFrame'>
Index: 11252 entries, 1 to 14999
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_id                 11252 non-null  str
 1   listing_date                11252 non-null  str
 2   property_type               11252 non-null  str
 3   city                        11252 non-null  str
 4   neighborhood_tier           11252 non-null  str
 5   zipcode_crime_rate          11252 non-null  float64
 6   school_rating               11252 non-null  int64
 7   distance_to_downtown_miles  11252 non-null  float64
 8   walk_score                  11252 non-null  int64
 9   bedrooms                    11252 non-null  int64
 10  bathrooms                   11252 non-null  float64
 11  square_feet                 11252 non-null  float64
 12  lot_size_sqft               11252 non-null  int64
 13  stories                     11252 non-null  int64
 14  garage_spaces               11252 non-null  int64
 15  year_built                  11252 non-null  int64
 16  house_age                   11252 non-null  int64
 17  has_basement                11252 non-null  str
 18  has_pool                    11252 non-null  str
 19  overall_condition           11252 non-null  str
 20  kitchen_quality             11252 non-null  str
 21  hvac_condition              11252 non-null  str
 22  roof_condition              11252 non-null  str
 23  renovation_year             4907 non-null   float64
 24  years_since_renovation      11252 non-null  int64
 25  days_on_market              11252 non-null  int64
 26  listing_season              11252 non-null  str
 27  market_trend                11252 non-null  str
 28  interest_rate               11252 non-null  float64
 29  has_fireplace               11252 non-null  str
 30  has_patio_deck              11252 non-null  str
 31  has_security_system         11252 non-null  str
 32  hoa_fees                    11252 non-null  float64
 33  sale_price                  11252 non-null  int64
 34  high_value_property         11252 non-null  str
dtypes: float64(7), int64(11), str(17)
memory usage: 3.1 MB

In [60]:
df_cleaned['renovation_year'] = df_cleaned['renovation_year'].fillna( df_cleaned['year_built']  )
df_cleaned.info()

<class 'pandas.DataFrame'>
Index: 11252 entries, 1 to 14999
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_id                 11252 non-null  str
 1   listing_date                11252 non-null  str
 2   property_type               11252 non-null  str
 3   city                        11252 non-null  str
 4   neighborhood_tier           11252 non-null  str
 5   zipcode_crime_rate          11252 non-null  float64
 6   school_rating               11252 non-null  int64
 7   distance_to_downtown_miles  11252 non-null  float64
 8   walk_score                  11252 non-null  int64
 9   bedrooms                    11252 non-null  int64
 10  bathrooms                   11252 non-null  float64
 11  square_feet                 11252 non-null  float64
 12  lot_size_sqft               11252 non-null  int64
 13  stories                     11252 non-null  int64
 14  garage_spaces               11252 non-null  int64
 15  year_built                  11252 non-null  int64
 16  house_age                   11252 non-null  int64
 17  has_basement                11252 non-null  str
 18  has_pool                    11252 non-null  str
 19  overall_condition           11252 non-null  str
 20  kitchen_quality             11252 non-null  str
 21  hvac_condition              11252 non-null  str
 22  roof_condition              11252 non-null  str
 23  renovation_year             11252 non-null  float64
 24  years_since_renovation      11252 non-null  int64
 25  days_on_market              11252 non-null  int64
 26  listing_season              11252 non-null  str
 27  market_trend                11252 non-null  str
 28  interest_rate               11252 non-null  float64
 29  has_fireplace               11252 non-null  str
 30  has_patio_deck              11252 non-null  str
 31  has_security_system         11252 non-null  str
 32  hoa_fees                    11252 non-null  float64
 33  sale_price                  11252 non-null  int64
 34  high_value_property         11252 non-null  str
dtypes: float64(7), int64(11), str(17)
memory usage: 3.1 MB